// Talocode MCP tool registry.
//
// TOOL_ROUTES maps each advertised tool name to the HTTP route that implements it.
// Derived from the tool definitions in Stacklane/apps/api/src/mcp/tools.ts, which carry an
// explicit route + method per tool.
//
// Only tools whose route this deploy can actually serve are advertised. Listing a tool that
// returns nothing is worse than not listing it: an agent that tries it concludes the platform
// is broken. Get /mcp reports both counts so the difference stays visible.

export const TOOL_ROUTES = {
  agent_browser_analyze: { route: '/v1/agent-browser/analyze', method: 'POST' },
  agent_browser_check: { route: '/v1/agent-browser/check', method: 'POST' },
  agent_browser_extract: { route: '/v1/agent-browser/extract', method: 'POST' },
  agent_browser_screenshot: { route: '/v1/agent-browser/screenshot', method: 'POST' },
  agent_browser_trace_report: { route: '/v1/agent-browser/trace-report', method: 'POST' },
  calclane_capabilities: { route: '/v1/calclane/capabilities', method: 'GET' },
  calclane_dispatch: { route: '/v1/calclane/dispatch', method: 'POST' },
  calclane_evaluate: { route: '/v1/calclane/evaluate', method: 'POST' },
  calclane_health: { route: '/v1/calclane/health', method: 'GET' },
  calclane_pricing: { route: '/v1/calclane/pricing', method: 'GET' },
  cliploop_brief_generate: { route: '/v1/cliploop/brief/generate', method: 'POST' },
  cliploop_campaign_create: { route: '/v1/cliploop/campaign/create', method: 'POST' },
  cliploop_campaign_package: { route: '/v1/cliploop/campaign/package', method: 'POST' },
  cliploop_script_generate: { route: '/v1/cliploop/script/generate', method: 'POST' },
  cliploop_video_render: { route: '/v1/cliploop/video/render', method: 'POST' },
  cloud_pricing: { route: '/api/v1/cloud/pricing', method: 'GET' },
  codra_review: { route: '/v1/codra/review', method: 'POST' },
  crawlerlane_404_analyze: { route: '/v1/crawlerlane/404/analyze', method: 'POST' },
  crawlerlane_ai_visibility_score: { route: '/v1/crawlerlane/ai-visibility/score', method: 'POST' },
  crawlerlane_bots_classify: { route: '/v1/crawlerlane/bots/classify', method: 'POST' },
  crawlerlane_export_json: { route: '/v1/crawlerlane/export/json', method: 'POST' },
  crawlerlane_export_markdown: { route: '/v1/crawlerlane/export/markdown', method: 'POST' },
  crawlerlane_logs_ingest: { route: '/v1/crawlerlane/logs/ingest', method: 'POST' },
  crawlerlane_pages_analyze: { route: '/v1/crawlerlane/pages/analyze', method: 'POST' },
  crawlerlane_report_generate: { route: '/v1/crawlerlane/report/generate', method: 'POST' },
  crawlerlane_robots_audit: { route: '/v1/crawlerlane/robots/audit', method: 'POST' },
  crawlerlane_sitemap_suggest: { route: '/v1/crawlerlane/sitemap/suggest', method: 'POST' },
  doculane_extract: { route: '/v1/doculane/extract', method: 'POST' },
  forgecad_assembly_plan: { route: '/v1/forgecad/assembly/plan', method: 'POST' },
  forgecad_bom_generate: { route: '/v1/forgecad/bom/generate', method: 'POST' },
  forgecad_cutlist_generate: { route: '/v1/forgecad/cutlist/generate', method: 'POST' },
  forgecad_design_generate: { route: '/v1/forgecad/design/generate', method: 'POST' },
  forgecad_design_review: { route: '/v1/forgecad/design/review', method: 'POST' },
  forgecad_export_json: { route: '/v1/forgecad/export/json', method: 'POST' },
  forgecad_export_markdown: { route: '/v1/forgecad/export/markdown', method: 'POST' },
  forgecad_manufacturability_check: { route: '/v1/forgecad/manufacturability/check', method: 'POST' },
  forgecad_material_estimate: { route: '/v1/forgecad/material/estimate', method: 'POST' },
  forgecad_openscad_generate: { route: '/v1/forgecad/openscad/generate', method: 'POST' },
  forgecad_printability_check: { route: '/v1/forgecad/printability/check', method: 'POST' },
  forgecad_render_openscad: { route: '/v1/forgecad/render/openscad', method: 'POST' },
  forgecad_tools_detect: { route: '/v1/forgecad/tools/detect', method: 'POST' },
  geolane_audit: { route: '/v1/geolane/audit', method: 'POST' },
  geolane_capabilities: { route: '/v1/geolane/capabilities', method: 'GET' },
  geolane_citation_readiness: { route: '/v1/geolane/citation-readiness', method: 'POST' },
  geolane_compare: { route: '/v1/geolane/compare', method: 'POST' },
  geolane_crawlers: { route: '/v1/geolane/crawlers', method: 'POST' },
  geolane_health: { route: '/v1/geolane/health', method: 'GET' },
  geolane_llms_txt: { route: '/v1/geolane/llms-txt', method: 'POST' },
  geolane_pricing: { route: '/v1/geolane/pricing', method: 'GET' },
  invoicelane_capabilities: { route: '/v1/invoicelane/capabilities', method: 'GET' },
  invoicelane_export_csv: { route: '/v1/invoicelane/export/csv', method: 'POST' },
  invoicelane_extract: { route: '/v1/invoicelane/extract', method: 'POST' },
  invoicelane_extract_invoice: { route: '/v1/invoicelane/invoice/extract', method: 'POST' },
  invoicelane_extract_receipt: { route: '/v1/invoicelane/receipt/extract', method: 'POST' },
  invoicelane_health: { route: '/v1/invoicelane/health', method: 'GET' },
  invoicelane_pricing: { route: '/v1/invoicelane/pricing', method: 'GET' },
  invoicelane_validate: { route: '/v1/invoicelane/validate', method: 'POST' },
  opensourcelane_alternatives_find: { route: '/v1/opensourcelane/alternatives/find', method: 'POST' },
  opensourcelane_brief_generate: { route: '/v1/opensourcelane/brief/generate', method: 'POST' },
  opensourcelane_cost_estimate: { route: '/v1/opensourcelane/cost/estimate', method: 'POST' },
  opensourcelane_deployment_plan: { route: '/v1/opensourcelane/deployment/plan', method: 'POST' },
  opensourcelane_export_json: { route: '/v1/opensourcelane/export/json', method: 'POST' },
  opensourcelane_export_markdown: { route: '/v1/opensourcelane/export/markdown', method: 'POST' },
  opensourcelane_license_audit: { route: '/v1/opensourcelane/license/audit', method: 'POST' },
  opensourcelane_migration_plan: { route: '/v1/opensourcelane/migration/plan', method: 'POST' },
  opensourcelane_repo_analyze: { route: '/v1/opensourcelane/repo/analyze', method: 'POST' },
  opensourcelane_risk_score: { route: '/v1/opensourcelane/risk/score', method: 'POST' },
  opensourcelane_tools_compare: { route: '/v1/opensourcelane/tools/compare', method: 'POST' },
  reliabilitylane_antipatterns: { route: '/v1/reliabilitylane/antipatterns', method: 'GET' },
  reliabilitylane_capabilities: { route: '/v1/reliabilitylane/capabilities', method: 'GET' },
  reliabilitylane_checklists: { route: '/v1/reliabilitylane/checklists', method: 'GET' },
  reliabilitylane_health: { route: '/v1/reliabilitylane/health', method: 'GET' },
  reliabilitylane_incident: { route: '/v1/reliabilitylane/incident', method: 'POST' },
  reliabilitylane_match: { route: '/v1/reliabilitylane/match', method: 'POST' },
  reliabilitylane_patterns: { route: '/v1/reliabilitylane/patterns', method: 'GET' },
  reliabilitylane_playbooks: { route: '/v1/reliabilitylane/playbooks', method: 'GET' },
  reliabilitylane_pricing: { route: '/v1/reliabilitylane/pricing', method: 'GET' },
  reliabilitylane_retries: { route: '/v1/reliabilitylane/retries', method: 'GET' },
  reliabilitylane_retry_plan: { route: '/v1/reliabilitylane/retry-plan', method: 'POST' },
  reliabilitylane_verify: { route: '/v1/reliabilitylane/verify', method: 'POST' },
  replylane_activity_audit: { route: '/v1/replylane/activity/audit', method: 'POST' },
  replylane_export_json: { route: '/v1/replylane/export/json', method: 'POST' },
  replylane_export_markdown: { route: '/v1/replylane/export/markdown', method: 'POST' },
  replylane_feeds_migrate: { route: '/v1/replylane/feeds/migrate', method: 'POST' },
  replylane_opportunity_score: { route: '/v1/replylane/opportunity/score', method: 'POST' },
  replylane_posts_grok_check: { route: '/v1/replylane/posts/grok-check', method: 'POST' },
  replylane_replies_draft: { route: '/v1/replylane/replies/draft', method: 'POST' },
  replylane_replies_risk: { route: '/v1/replylane/replies/risk', method: 'POST' },
  replylane_targets_rank: { route: '/v1/replylane/targets/rank', method: 'POST' },
  searchlane_capabilities: { route: '/v1/searchlane/capabilities', method: 'GET' },
  searchlane_health: { route: '/v1/searchlane/health', method: 'GET' },
  searchlane_news: { route: '/v1/searchlane/news', method: 'POST' },
  searchlane_pricing: { route: '/v1/searchlane/pricing', method: 'GET' },
  searchlane_query: { route: '/v1/searchlane/query', method: 'POST' },
  searchlane_research: { route: '/v1/searchlane/research', method: 'POST' },
  signallane_x_analyze: { route: '/v1/signallane/x/analyze', method: 'POST' },
  signallane_x_content_plan: { route: '/v1/signallane/x/content-plan', method: 'POST' },
  signallane_x_experiments: { route: '/v1/signallane/x/experiments', method: 'POST' },
  signallane_x_post_drafts: { route: '/v1/signallane/x/post-drafts', method: 'POST' },
  signallane_x_report: { route: '/v1/signallane/x/report', method: 'POST' },
  skills_export_claude: { route: '/v1/skills/export/claude', method: 'POST' },
  skills_export_cursor: { route: '/v1/skills/export/cursor', method: 'POST' },
  skills_generate_docs: { route: '/v1/skills/generate/docs', method: 'POST' },
  skills_generate_github_profile: { route: '/v1/skills/generate/github-profile', method: 'POST' },
  skills_generate_github_repo: { route: '/v1/skills/generate/github-repo', method: 'POST' },
  skills_generate_recording: { route: '/v1/skills/generate/recording', method: 'POST' },
  skills_generate_text: { route: '/v1/skills/generate/text', method: 'POST' },
  tera_coding_explain: { route: '/v1/tera/coding/explain', method: 'POST' },
  tera_coding_review: { route: '/v1/tera/coding/review', method: 'POST' },
  tera_writing_draft: { route: '/v1/tera/writing/draft', method: 'POST' },
  tera_writing_rewrite: { route: '/v1/tera/writing/rewrite', method: 'POST' },
  tradia_accountability_card: { route: '/v1/tradia/accountability/card', method: 'POST' },
  tradia_agent_plan: { route: '/v1/tradia/agent/plan', method: 'POST' },
  tradia_backtest_simulate: { route: '/v1/tradia/backtest/simulate', method: 'POST' },
  tradia_export_json: { route: '/v1/tradia/export/json', method: 'POST' },
  tradia_export_markdown: { route: '/v1/tradia/export/markdown', method: 'POST' },
  tradia_health: { route: '/v1/tradia/health', method: 'GET' },
  tradia_market_analyze: { route: '/v1/tradia/market/analyze', method: 'POST' },
  tradia_performance_analyze: { route: '/v1/tradia/performance/analyze', method: 'POST' },
  tradia_portfolio_report: { route: '/v1/tradia/portfolio/report', method: 'POST' },
  tradia_public_update_generate: { route: '/v1/tradia/public-update/generate', method: 'POST' },
  tradia_risk_check: { route: '/v1/tradia/risk/check', method: 'POST' },
  tradia_signal_evaluate: { route: '/v1/tradia/signal/evaluate', method: 'POST' },
  tradia_trade_journal: { route: '/v1/tradia/trade/journal', method: 'POST' },
  tradia_trade_propose: { route: '/v1/tradia/trade/propose', method: 'POST' },
  ugclane_accounts_plan: { route: '/v1/ugclane/accounts/plan', method: 'POST' },
  ugclane_calendar_generate: { route: '/v1/ugclane/calendar/generate', method: 'POST' },
  ugclane_competitor_analyze: { route: '/v1/ugclane/competitor/analyze', method: 'POST' },
  ugclane_experiments_generate: { route: '/v1/ugclane/experiments/generate', method: 'POST' },
  ugclane_export_json: { route: '/v1/ugclane/export/json', method: 'POST' },
  ugclane_export_markdown: { route: '/v1/ugclane/export/markdown', method: 'POST' },
  ugclane_hooks_generate: { route: '/v1/ugclane/hooks/generate', method: 'POST' },
  ugclane_report_generate: { route: '/v1/ugclane/report/generate', method: 'POST' },
  ugclane_scripts_generate: { route: '/v1/ugclane/scripts/generate', method: 'POST' },
  ugclane_strategy_generate: { route: '/v1/ugclane/strategy/generate', method: 'POST' },
  webdatalane_crawl_plan: { route: '/v1/webdatalane/crawl/plan', method: 'POST' },
  webdatalane_extract: { route: '/v1/webdatalane/extract', method: 'POST' },
  webdatalane_fetch: { route: '/v1/webdatalane/fetch', method: 'POST' },
  webdatalane_links: { route: '/v1/webdatalane/links', method: 'POST' },
  webdatalane_markdown: { route: '/v1/webdatalane/markdown', method: 'POST' },
  webdatalane_metadata: { route: '/v1/webdatalane/metadata', method: 'POST' },
  webdatalane_screenshot: { route: '/v1/webdatalane/screenshot', method: 'POST' },
  webdatalane_structured: { route: '/v1/webdatalane/structured', method: 'POST' },
}

export const AVAILABLE_FAMILIES = [
  '/v1/agent-browser/',
  '/v1/audiolane/',
  '/v1/calclane/',
  '/v1/capabilities/',
  '/v1/cliploop/',
  '/v1/datalane/',
  '/v1/doculane/',
  '/v1/gateway/',
  '/v1/geolane/',
  '/v1/handofflane/',
  '/v1/invoicelane/',
  '/v1/policylane/',
  '/v1/reliabilitylane/',
  '/v1/searchlane/',
  '/v1/skills/',
  '/v1/spendcaps/',
  '/v1/stylelane/',
  '/v1/tera/',
  '/v1/tracelane/',
  '/v1/verifylane/',
  '/v1/videolane/',
  '/v1/wiki/',
  '/v1/worklane/',
]

// Routes served by an exact path match rather than a family prefix.
export const AVAILABLE_EXACT_ROUTES = [
  '/',
  '/api/v1/cloud/billing/lemonsqueezy/webhook',
  '/api/v1/cloud/billing/packs',
  '/api/v1/cloud/billing/topup',
  '/api/v1/cloud/billing/topup/confirm',
  '/api/v1/cloud/health',
  '/api/v1/cloud/pricing',
  '/api/v1/cloud/projects',
  '/api/v1/cloud/tcode',
  '/api/v1/cloud/tcode/challenge',
  '/api/v1/cloud/tcode/claim',
  '/api/v1/cloud/tcode/holdings',
  '/api/v1/cloud/tcode/link',
  '/api/v1/cloud/tcode/price',
  '/api/v1/cloud/tcode/purchase',
  '/api/v1/cloud/tcode/purchase/quote',
  '/api/v1/cloud/tcode/purchases',
  '/api/v1/cloud/usage/charge',
  '/auth/admin/delete-user',
  '/auth/login',
  '/auth/logout',
  '/auth/me',
  '/auth/register',
  '/capabilities',
  '/cloud/health',
  '/health',
  '/health/storage',
  '/mcp',
  '/organizations',
  '/pricing',
  '/projects',
  '/regions',
  '/v1/capabilities',
  '/v1/chat/completions',
  '/v1/cliploop/',
  '/v1/cliploop/brief/generate',
  '/v1/cliploop/campaign/create',
  '/v1/cliploop/campaign/package',
  '/v1/cliploop/capabilities',
  '/v1/cliploop/health',
  '/v1/cliploop/pricing',
  '/v1/cliploop/script/generate',
  '/v1/cliploop/video/render',
  '/v1/codra/repo-summary',
  '/v1/codra/run',
  '/v1/datalane/',
  '/v1/datalane/analyze',
  '/v1/datalane/capabilities',
  '/v1/datalane/health',
  '/v1/datalane/pricing',
  '/v1/datalane/render',
  '/v1/gatelane/call',
  '/v1/health',
  '/v1/router/chat/completions',
  '/v1/router/health',
  '/v1/screenlane/command',
  '/v1/screenlane/demo',
  '/v1/screenlane/doctor',
  '/v1/screenlane/health',
  '/v1/screenlane/send',
  '/v1/telemetry/ping',
  '/v1/tera/writing/rewrite',
]

// Implemented in-process rather than proxied to a product route.
// An API key can spend credits but previously could not read its own balance or usage.
export const INTERNAL_TOOLS = [
  {
    name: 'cloud_credits_balance',
    description: 'Check credit balance, lifetime credits and lifetime spend for the project this API key belongs to. Free.'
  },
  {
    name: 'cloud_usage_recent',
    description: 'List recent metered usage events for this API key: product, action, credits, status, timestamp. Free. Optional limit (default 20, max 100).'
  },
]

export function routeFamily(route) {
  const parts = String(route || '').split('/')
  return parts.length >= 3 ? '/' + parts[1] + '/' + parts[2] + '/' : ''
}

export function isDispatchable(name) {
  const entry = TOOL_ROUTES[name]
  if (!entry) return false
  return AVAILABLE_FAMILIES.includes(routeFamily(entry.route)) || AVAILABLE_EXACT_ROUTES.includes(entry.route)
}

export function isInternal(name) {
  return INTERNAL_TOOLS.some((t) => t.name === name)
}

export function workingToolNames() {
  return Object.keys(TOOL_ROUTES).filter(isDispatchable).sort().concat(INTERNAL_TOOLS.map((t) => t.name))
}
